name: roble_api_database
description: Cliente HTTP para interactuar con el backend Roble API.
version: 1.0.2
homepage: https://github.com/Arias3/roble_api_database
repository: https://github.com/Arias3/roble_api_database

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
